name: Issue to HTML

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2

    - name: Generate HTML from issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python generate_html.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" "${{ github.event.issue.number }}"

    - name: Commit HTML file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add issue_${{ github.event.issue.number }}.html
        git commit -m "Add HTML presentation for issue #${{ github.event.issue.number }}"
        git push

